### ISSUE TITLE
not able to install dependencies

### ISSUE THREAD

**Issue by ethicalhacker7192** [safesploit/PythonRAT#1]
all installations including python went well except for the dependencies as seen below
![Screenshot_2022-08-09_13_37_35](https://user-images.githubusercontent.com/107788660/183746537-93416d4f-923d-4676-99a7-8d7236bc5628.png)
.

**Comment by safesploit** [comment]
Strange, I have been experiencing similar issues with older versions of PIP.
I will investigate!

Fortunately, since [v0.10.1-alpha](https://github.com/safesploit/PythonRAT/releases/tag/v0.10.1), I have deprecated PyAutoGUI in favour of MSS for the screenshot function.
Because I made this change yesterday I have yet to update the README.md.

**Comment by ethicalhacker7192** [comment]
i have found a way around the PyAutoGUI by doing command pip install PyAutoGUI But now I am facing a different problem as seen below![Screenshot_2022-08-10_01_07_05](https://user-images.githubusercontent.com/107788660/183837217-062c9084-5b80-4e1f-abcc-b9f14eec1254.png)

**Comment by ethicalhacker7192** [comment]
whoops new error message popped up
![Screenshot_2022-08-10_01_19_00](https://user-images.githubusercontent.com/107788660/183839352-dc2a9a54-7d1a-41e9-a1b4-821478b3bce8.png)

**Comment by safesploit** [comment]
> whoops new error message popped up ![Screenshot_2022-08-10_01_19_00]

The problem is Pyinstaller will produce an OS dependent executable, Linux=ELF and Windows=PE32. I put this part using Wine and Pyinstaller to overcome having to compile the backdoor in a Windows 7 environment, apparently this still needs more work.

I know in Windows 7 installing `python-2.7.14.msi` and configuring as such

`python.exe -m pip install pyinstaller requests pynput mss`
`pyinstaller.exe --onefile --noconsole PythonRAT\backdoor\backdoor.py`

will produce a PE32 executable capable.

I will make attempts to overcome this issue, but Pyinstaller with its OS dependency gave me many issues in the past.

**Comment by safesploit** [comment]
<img width="1754" alt="image" src="https://user-images.githubusercontent.com/10171446/183861004-a2e77bc8-b392-4a5b-a1d6-b618c8313a8d.png">

If you want to test the project, just install the dependencies with pip and run the backdoor.py with Python3 as shown above.

**Comment by ethicalhacker7192** [comment]
thank you I have finally got it working as intended
